modLoader="javafml"
loaderVersion="${mod_forge_version}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/anti-mob-griefing/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/antimobgriefing.json"
displayURL="https://modrepo.de"
# logoFile="antimobgriefing.png"
# credits=""
authors="${mod_vendor}"
description='''Anti Mobgriefing'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"